### ISSUE TITLE
Same property is displayed twice

### ISSUE THREAD

**Issue by DumontJulie** [voyages-sncf-technologies/hesperides#77]
On the screen displaying all properties for one module and one plaftorm, one of our property is displayed twice, and only one is valued.
This occurs on a VSCT project : GEL, for the module gel-back working copy. 

![image](https://user-images.githubusercontent.com/31069238/29364353-6c7de20c-8293-11e7-9101-3bc776453cf9.png)

**Comment by JordanKergoat** [comment]
Hello,
Actually, if you want to avoid this funny stuff, you need to make sure that, every time you use the same property in your template, to have the exact same model. Otherwise Hesperides will consider them as different properties. 

E.g : {{foo|@password}} !=  {{foo}}

So in you case, you need to repeat the exact same model (with the default value and comment) on each occurence of gel.back.dir.file.export.root.path. 

I know that is not a real solution to do that, we are currently aware of this problem and we are trying to find the best way to handle theses cases.

If you try to fill this property you will see that one of the input will disapear and your file will be generated with the value you inputed in each occurence of your template.

**Comment by Lucas-C** [comment]
Fermé au profit de https://github.com/voyages-sncf-technologies/hesperides/issues/77
